### ISSUE TITLE
How can i remove fields?

### ISSUE THREAD

**Issue by inzamamabbasi** [christianwach/bp-xprofile-wp-user-sync#5]
I added the plugin to sync buddypress profile firstname and lastname with wordpress But when i deactivate the plugin auto added fields are still there .

I want when i deactivate the plugin field should go as well Now every one i activate plugin it add another 2 fields firstname and lastname 
https://i.imgur.com/NfHmfrc.png
And there is no delete option on this fields

**Comment by christianwach** [comment]
@inzamamabbasi Yeah, this whole situation is a bit of a nightmare because of the way BuddyPress handles xProfile fields provided programatically via plugins. The [comments in the code](https://github.com/christianwach/bp-xprofile-wp-user-sync/blob/master/bp-xprofile-wp-user-sync.php#L221-L233) explain this at length.

If your install isn't firing [the `deactivate` hook](https://github.com/christianwach/bp-xprofile-wp-user-sync/blob/master/bp-xprofile-wp-user-sync.php#L1139), then [the `deactivate()` method](https://github.com/christianwach/bp-xprofile-wp-user-sync/blob/master/bp-xprofile-wp-user-sync.php#L219) won't fire and this plugin won't delete the fields. You will have to debug why that is.

**Comment by inzamamabbasi** [comment]
Strange :( okay i deactivate both extended profile feature with this plugin .. Now i am going to build it with different way

**Comment by christianwach** [comment]
@inzamamabbasi Gotcha, sorry I can't be of more help.
