### ISSUE TITLE
Sync bp-xprofile with acf field ? 

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/bp-xprofile-wp-user-sync#6]
Hi Christian :) 

Hope you're doing well :)

I wonder if this plug-in, can sync bp-xpfofile with acf field ? 

Or but this is rather a bp question, if we could edit acf field from bp front end user page ? 

This questions rises now as I've seen you've recently updated CiviCRM Profile Sync, to merge Civi-acf integration, which is awesome, as always ! 
So the idea is to use the great power of Acf-civi field syncing, and the bp front end machinery to allow the site visitors (users/contact) to handle their personal data, etc.

Thank's for the excellent work !!

**Comment by christianwach** [comment]
@jbonlinea I'm going to retire this plugin when BuddyPress 8 comes out because it should contain better syncing of xProfile fields with WordPress user fields. You can try it out with the core BuddyPress patch here:

https://buddypress.trac.wordpress.org/ticket/7162

I just have to write a migration script for this plugin before BuddyPress 8.

**Comment by jbonlinea** [comment]
Hi

Oh, ok, good to know, I've read the discussion over there, this is indeed promising.

My belly button says, I haven't used this plug-in yet, and I most certainly won't as I'll probably avoid a lot of hassle by simply building a from to edit user acf field or civi-contact field. This will do the job I want now, and I'll see how to bring it to bp once v8 is released.


Than'ks
